### ISSUE TITLE
[Suggestion] PS scripts: Put the sorted property first

### ISSUE THREAD

**Issue by mortenlerudjordet** [squaredup/Community.DataOnDemand.MP#25]
This might just be a personal preference, though I will leave this up to others.

For the PS scripts put the property being sorted at the front.

Current:
        | Sort-Object -Property Name `
        | Select-Object DisplayName, Status, Name 

Proposed:
        | Sort-Object -Property Name `
        | Select-Object Name, Status, DisplayName 

In my opinion this looks better when running an on demand task.
But I will let others decide.

**Comment by shadeon** [comment]
Hi Morten,

Good idea, I'd agree it makes for more natural reading (especially in the case of sorting on datetime).

We happily accept pull requests on this repo (targeting the develop branch), so if you have the time feel free to make the changes you outlined above and submit them.  Do watch out for the tasks that allow the caller to specify the ordering property - you'll want to make sure you account for this in the Select-Object.

**Comment by mortenlerudjordet** [comment]
I'll give it a whack when I have some spare time.

**Comment by mortenlerudjordet** [comment]
I have created a pull request for the suggested changes here: https://github.com/squaredup/Community.DataOnDemand.MP/pull/27

**Comment by mortenlerudjordet** [comment]
Closing this as my code suggestion is merged in
