### ISSUE TITLE
Get Netstat CSV (Data On Demand) for Linux is failing & not retrieving any information

### ISSUE THREAD

**Issue by SPostea** [squaredup/Community.DataOnDemand.MP#39]
The problem lies with the Microsoft.SystemCenter.WSManagement.Library!Microsoft.SystemCenter.WSManagement.Invoker ProbeAction type used in the workflow.
It doesn’t work in SCOM 2019!!

MicrosoftUnixShellCommandLibrary!Microsoft.Unix.Invoke.Script.ProbeAction must be used instead, with the GetNetstatCSV.sh script encoded Base64.

Also, there are problems with the script itself as netstat might return LOTS of ESTABLISHED TCP connections.
Some kind of limit or process filtering must be put in place at script level (via arguments), otherwise script will time out without returning anything.

**Comment by shawn149** [comment]
Closing as not reproducible.
